language: java

# Cobertura is not supported in JDK11 so you must downgrade the JDK that Travis uses if you want to use Cobertura with Travis.
# https://github.com/cobertura/cobertura/issues/381
jdk:
  - openjdk8

# Faster Builds
sudo: false

# Blocklist & Safelist
branches:
  except:
    - /dev\/\w+/
  only:
    - main

script:
  - mvn clean install
  - mvn package
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)